### ISSUE TITLE
[1.11.2] Crash when placing a (advanced?) monitor next to a Computer on a server

### ISSUE THREAD

**Issue by Lordmau5** [NoMansMinecraft/Computality#29] opened 2017-07-16 23:41 UTC
https://pastebin.com/2kCxXeiu

So yea. Did literally nothing other than placing down a advanced monitor next to a Advanced Computer.
Game crashed and now I can't join my server anymore.

Funnily enough it only crashes the client, not the server.

**Comment by TheCodedOne** [comment] 2017-07-16 23:45
Duplicate of #14

**Closed by TheCodedOne** 2017-07-16 23:45 UTC
Labels: duplicate
